
title: "situation vécue"
description: "근사치"
theme: minima

  name: "Yeonsu"

minima:
  skin: classic

# Show these pages in the top navigation
header_pages:
  - journal.md
  - notes.md
  - library.md
  - study.md
  - contact.md

plugins:
  - jekyll-feed
